# Generated by Django 4.0.2 on 2022-02-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_incomesource_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='categories',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='categories',
            field=models.ManyToManyField(to='api.Category'),
        ),
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.ManyToManyField(to='api.Source'),
        ),
    ]
