# Generated by Django 4.0.2 on 2022-02-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_income_categories_alter_expenses_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_title',
            field=models.CharField(max_length=50),
        ),
    ]
